/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-13 03:19:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mini;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class miniBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1683857980997L));
    _jspx_dependants.put("jar:file:/C:/D/SemiProj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1_Gorri/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/views/mini/../common/footer.jsp", Long.valueOf(1683370104804L));
    _jspx_dependants.put("/WEB-INF/views/mini/../common/top.jsp", Long.valueOf(1683957772183L));
    _jspx_dependants.put("/WEB-INF/views/mini/minihome-nav.jsp", Long.valueOf(1683947039205L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\"> <!-- 폰트 아이콘 사용할수있게 -->\r\n");
      out.write("	\r\n");
      out.write("<title>Gorri</title>\r\n");
      out.write("<style>\r\n");
      out.write("	\r\n");
      out.write("	/* 주황 테두리 부분 */\r\n");
      out.write("	.border-line{\r\n");
      out.write("		border : 2px solid #ffaa00; width : 1200px; \r\n");
      out.write("		margin-top: 100px;\r\n");
      out.write("		margin-left:auto; margin-right:auto;\r\n");
      out.write("		border-top-left-radius: 30px; border-top-right-radius: 30px; border-bottom-left-radius: 30px; border-bottom-right-radius: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("<!-- 	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> -->\r\n");
      out.write("	<title>Bootstrap demo</title>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("	<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("	<style>\r\n");
      out.write("		.bg{background-color: #FFAB00;}\r\n");
      out.write("		.navbar{height: 50px;}\r\n");
      out.write("		.image{height: 250px;}\r\n");
      out.write("		.mar{margin-left: 100px; margin-right: 100px;}\r\n");
      out.write("		.bo{border-top: 1px solid black; border-bottom: 1px solid black;}\r\n");
      out.write("		.a{font-weight: bold;}\r\n");
      out.write("	</style>\r\n");
      out.write("<script src=\"../js/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"navbar bg shadow-sm\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("	     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	  	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do\">\r\n");
      out.write("		<img src=\"resources/assets/gorriLogo.png\" class=\"rounded\" alt=\"...\">\r\n");
      out.write("	</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"nav-scroller py-1 mb-2 mar\">\r\n");
      out.write("    <nav class=\"nav d-flex justify-content-around bo\">\r\n");
      out.write("      <div> </div>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/miniMain.mi\">미니홈</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hobbyMain.hb\">취미</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupMain.gr\">모임</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"#\">마켓</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"#\">공지</a>\r\n");
      out.write("      <div> </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"border-line\"> <!-- 겉에 주황색 테두리 -->\r\n");
      out.write("   \r\n");
      out.write("   		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\"> <!-- 폰트 아이콘 사용할수있게 -->\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	/* top - 프로필 사진 동그라미 부분*/\r\n");
      out.write("	.top-profile-img{\r\n");
      out.write("		position:relative;\r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		margin-top: -75px;\r\n");
      out.write("		margin-bottom: 150px;}\r\n");
      out.write("	#profile-back{ /* 맨뒤에 주황*/\r\n");
      out.write("		width: 150px; height: 75px;\r\n");
      out.write("		background: #ffaa00;\r\n");
      out.write("		border-radius: 75px 75px 0 0;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		}\r\n");
      out.write("	#profile-white{ /* 가운데 흰색 */\r\n");
      out.write("		width: 146px; height:146px;\r\n");
      out.write("		background: white;\r\n");
      out.write("		border-radius: 50%;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		margin-top: 1.5px;\r\n");
      out.write("		}\r\n");
      out.write("	#profile{width: 130px; height: 130px;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		margin-top: 8.5px;\r\n");
      out.write("		}\r\n");
      out.write("	#profile-img{width: 100%; height: 100%; \r\n");
      out.write("		border-radius: 50%;\r\n");
      out.write("		object-fit: cover;\r\n");
      out.write("		object-position: center;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/* 닉네임, 간단소개 태그 부분 */\r\n");
      out.write("	.mid-width{width: 80%; margin-bottom: 20px;}\r\n");
      out.write("	.mid-info{\r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		margin-bottom: 10px;	\r\n");
      out.write("		}\r\n");
      out.write("	#id{ /*닉네임*/\r\n");
      out.write("		text-align: center; font-weight: bold;\r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		margin-right: 5px;\r\n");
      out.write("		}\r\n");
      out.write("	#edit-icon{width: 15px; height: 15px; cursor: pointer; transition: all 0.3s ease 0s;} /*프로필 수정 아이콘*/\r\n");
      out.write("	#edit-icon:hover{\r\n");
      out.write("		color: #ffaa00; background: white;\r\n");
      out.write("		cursor: pointer; \r\n");
      out.write("		transform: translateY(-7px);\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	/* 마이홈 메뉴관련 - 게시글, 모임, 구매내역 */\r\n");
      out.write("	.minihome{\r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		}\r\n");
      out.write("	.minihome-btn-width{width: 80%;\r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		}\r\n");
      out.write("	.empty{width: 10%; text-align: right;}\r\n");
      out.write("	\r\n");
      out.write("	.footer{\r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items : center;\r\n");
      out.write("		margin-top: 10px; margin-bottom: 30px;\r\n");
      out.write("		padding-top: 20px;\r\n");
      out.write("		border-top: 1px solid lightgray;\r\n");
      out.write("		}\r\n");
      out.write("	.button {\r\n");
      out.write("	  width: 100px; height: 45px;\r\n");
      out.write("	  font-family: ;\r\n");
      out.write("	  font-size: 13px;\r\n");
      out.write("	  letter-spacing: 2.5px;\r\n");
      out.write("	  font-weight: 500;\r\n");
      out.write("	  color: #000;\r\n");
      out.write("	  background-color: #fff;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-radius: 45px;\r\n");
      out.write("	  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	  transition: all 0.3s ease 0s;\r\n");
      out.write("	  cursor: pointer;\r\n");
      out.write("	  outline: none;\r\n");
      out.write("	  margin: 5px;\r\n");
      out.write("	  }\r\n");
      out.write("	.button:hover {\r\n");
      out.write("		background-color: #ffaa00;\r\n");
      out.write("		box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		color: #fff;\r\n");
      out.write("		transform: translateY(-7px);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.select{background: black; color: white;} /* 현재 선택된 버튼 -> 현재 선택된페이지는 버튼색깔 다르게 해줘야 함요!!*/ \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/* 글쓰기 버튼 */\r\n");
      out.write("	.bi-pencil-square{font-size: 20px;  transition: all 0.3s ease 0s;}\r\n");
      out.write("	.bi-pencil-square:hover{\r\n");
      out.write("		color: #ffaa00; background: white;\r\n");
      out.write("		cursor: pointer; \r\n");
      out.write("		transform: translateY(-7px);}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/* 중간 줄*/\r\n");
      out.write("	.mid-line{\r\n");
      out.write("		border : 1px solid gray; width: 90%;\r\n");
      out.write("		margin-left:auto; margin-right:auto; margin-top: 20px; margin-bottom: 20px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	/* 프로필 수정 창 */\r\n");
      out.write("	.modal-body{margin-left:auto; margin-right:auto;}\r\n");
      out.write("	.edit{margin: 0 auto; text-align: center;}\r\n");
      out.write("	textarea{resize: none; width: 400px; height: 100px;} /* resize: none;이 여기선 왜 적용 안됨??*/\r\n");
      out.write("	#edit-img{width: 130px; height:130px; /* 프로필 이미지 */\r\n");
      out.write("		margin-left:auto; margin-right:auto;;\r\n");
      out.write("		border-radius: 50%;\r\n");
      out.write("		background-image: url('assets/no-img.png');\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("    	background-position: center;\r\n");
      out.write("    	background-size : 130px, 130px;\r\n");
      out.write("    	margin-bottom: 20px\r\n");
      out.write("		}\r\n");
      out.write("	.input-file-button{ /* 파일입력창 못생겨서 만든 가짜 입력버튼..*/\r\n");
      out.write("		border: 2.8px solid white; border-radius: 15px;\r\n");
      out.write("		background: #ffaa00; color: black;  cursor: pointer; font-size: 14px;\r\n");
      out.write("		padding-left: 4px; padding-right: 4px;\r\n");
      out.write("		margin-left: 95px; margin-top: 95px;}\r\n");
      out.write("	.input-file-button:hover{background: black; color: #ffaa00; font-size: 14px;}	\r\n");
      out.write("	#input-file{display: none;} /* 파일 버튼 안보이게.. */\r\n");
      out.write("	.modal-footer{text-align: center;}\r\n");
      out.write("	.modal-footer> .button{font-weight: bold;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 프로필사진 관련 -->\r\n");
      out.write("	<div class=\"top-profile-img\"> \r\n");
      out.write("		<div id=\"profile-back\"></div>\r\n");
      out.write("		<div id=\"profile-white\"></div>\r\n");
      out.write("		<div id=\"profile\">\r\n");
      out.write("			<img id=\"profile-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/no-img.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 프로필 정보 관련 -->\r\n");
      out.write("	<div class=\"mid\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- id, 자기소개 -->\r\n");
      out.write("		<div class=\"minihome\">\r\n");
      out.write("			<div class=\"mid-width\">\r\n");
      out.write("				<div class=\"mid-info\">\r\n");
      out.write("					<div id=\"id\">닉네임</div>\r\n");
      out.write("					<div><i class=\"bi bi-gear-fill\" id=\"edit-icon\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\"></i></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div> <!-- 칸 안늘어나게 하기위해서 크기 미리 정해놔야 할듯 -->\r\n");
      out.write("					<div>자기소개글이 여기에 출력됩니다~ 자기소개글을 올려보세요 내 이름은 최정흠 입니다. 최대 몇글자인지 정해놔야 할듯! 칸 고정? 아님 쓰는데로 늘어나게??</div>\r\n");
      out.write("				</div> \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<!-- 게세글, 모임, 구매내역 버튼 --> <!-- 선택된 버튼은 클래스에 select넣어야 선택된 상태일때 색 바뀜 -->\r\n");
      out.write("		<div class=\"minihome\">\r\n");
      out.write("			<div class=\"minihome-btn-width\">\r\n");
      out.write("				<div class=\"empty\"></div>\r\n");
      out.write("				<div><button class=\"button\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/miniMain.mi';\"><b>게시글</b></button></div>\r\n");
      out.write("				<div><button class=\"button\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/miniMoim.mi';\"><b>모임</b></button></div>\r\n");
      out.write("				<div><button class=\"button\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/miniBuy.mi';\"><b>구매내역</b></button></div>\r\n");
      out.write("				<div class=\"empty\"><a onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/miniBoard.mi';\"><i class=\"bi bi-pencil-square\"></i></a></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"mid-line\"></div>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- Modal --> <!-- 프로필 수정 버튼 클릭하면 뜨는 프로필 수정페이지 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h5 class=\"modal-title\" id=\"exampleModalLabel\">프로필 수정</h5>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("	      </div>\r\n");
      out.write("		    <div class=\"modal-body\">\r\n");
      out.write("		    	<table class=\"edit\">\r\n");
      out.write("		    		<tr>\r\n");
      out.write("		    			<td>\r\n");
      out.write("		    				<div id=\"edit-img\">\r\n");
      out.write("		    					<label class=\"input-file-button\" for=\"input-file\"><i class=\"bi bi-camera-fill\"></i></label>\r\n");
      out.write("		    					<input class=\"form-con\" type=\"file\" id=\"input-file\">\r\n");
      out.write("							</div>\r\n");
      out.write("		    			</td>\r\n");
      out.write("		    		</tr>\r\n");
      out.write("		    		<tr>\r\n");
      out.write("		    			<td>\r\n");
      out.write("		    				<textarea class=\"edit-text\" style=\"resize: none;\" placeholder=\"자기소개를 입력해주세요.\"></textarea>\r\n");
      out.write("		    			</td>\r\n");
      out.write("		    		</tr>\r\n");
      out.write("		    	</table>\r\n");
      out.write("			</div>\r\n");
      out.write("	      <div class=\"footer\">\r\n");
      out.write("	        <button type=\"button\" class=\"button\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("	        <button type=\"button\" class=\"button\">저장</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" <!-- 프로필사진, 닉넴, 자기소개글, 메뉴버튼 -->\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"bottom\">\r\n");
      out.write("			여기에 글쓰는 게시판 만들기\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr></tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	 <script src=\"https://kit.fontawesome.com/243bcd4d8b.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.footer-bg{background: rgba(255, 170, 0, 0.7); width: 100%;} /*헤더 색깔은 #FFAB00*/\r\n");
      out.write("	\r\n");
      out.write("	.text{color: white;}\r\n");
      out.write("	.logo{width: 200px;}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    <title>Gorri</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("    <!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->\r\n");
      out.write("    <br><br>\r\n");
      out.write("<div class=\"footer-bg\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	  <footer class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4\">\r\n");
      out.write("	    <p class=\"col-md-4 mb-0 text\">&copy; 2023 Company, Inc</p>\r\n");
      out.write("	\r\n");
      out.write("	    <a href=\"/\" class=\"col-md-4 d-flex align-items-center justify-content-center\">\r\n");
      out.write("	      <img class=\"logo\" src=\"resources/assets/gorriLogo.png\">\r\n");
      out.write("	    </a>\r\n");
      out.write("	    \r\n");
      out.write("	    <ul class=\"nav col-md-4 justify-content-end\">\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\">Home</a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\"><i class=\"fa-brands fa-twitter\"></i></a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\"><i class=\"fa-brands fa-facebook\"></i></a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\"><i class=\"fa-brands fa-instagram\"></i></a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\">About</a></li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	  </footer>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/mini/../common/top.jsp(23,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mini/../common/top.jsp(23,0) '${ pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/mini/../common/top.jsp(23,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/mini/../common/top.jsp(23,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/mini/../common/top.jsp(27,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		     <nav class=\"d-inline-flex mt-md-0 ms-md-auto\">\r\n");
          out.write("		       <a class=\"me-3 py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login.me\">로그인</a>\r\n");
          out.write("		       <a class=\"py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/join.me\">회원가입</a>\r\n");
          out.write("		     </nav>\r\n");
          out.write("		  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/mini/../common/top.jsp(33,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \r\n");
          out.write("				  	\r\n");
          out.write("	     <nav class=\"d-inline-flex mt-md-0 ms-md-auto\">\r\n");
          out.write("	     	   <a class=\"me-3 py-2 text-white text-decoration-none\" style=\"color:lightgrey\" disabled >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</a>\r\n");
          out.write("		       <a class=\"me-3 py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout.me\">로그아웃</a>\r\n");
          out.write("		       <a class=\"py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/updateMyInfo.me\">내정보수정</a>\r\n");
          out.write("		       ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	     </nav>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/mini/../common/top.jsp(39,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.isAdmin eq 'Y' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		       &nbsp; &nbsp; <a class=\"py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/adminDash.ad\">관리자페이지</a>\r\n");
          out.write("		       ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
