/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-13 05:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.group;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class groupMain2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/group/../common/top.jsp", Long.valueOf(1683957772183L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1683857980997L));
    _jspx_dependants.put("jar:file:/C:/D/SemiProj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1_Gorri/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/views/group/../common/category.jsp", Long.valueOf(1683369998990L));
    _jspx_dependants.put("/WEB-INF/views/group/../common/footer.jsp", Long.valueOf(1683370104804L));
    _jspx_dependants.put("/WEB-INF/views/group/../common/search.jsp", Long.valueOf(1683592752699L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("	.gTitle{text-align:center; text-decoration:underline;}\n");
      out.write("/* 	.groupCARD{width:350px; margin-left:auto; margin-right:auto; margin-top:20px; margin-bottom:20px;} */\n");
      out.write("/* 	.groupName{font-size: 30px; font-weight:bold;} */\n");
      out.write("/* 	.groupInt{heigt:100px;} */\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	.groupTable2{\n");
      out.write("		border-collapse:separate;\n");
      out.write("		border-spacing:0;\n");
      out.write("		margin: 20px;\n");
      out.write("		width:880px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.groupPic{\n");
      out.write("		width:300px;\n");
      out.write("		height:300px;\n");
      out.write("		position:relative;\n");
      out.write("		overflow:hidden;\n");
      out.write("		-webkit-clip-path: padding-box;\n");
      out.write("    	clip-path: padding-box;\n");
      out.write("	}\n");
      out.write("	.groupTitle{\n");
      out.write("		height:40px;\n");
      out.write("		font-size:30px;\n");
      out.write("		font-weight:bold;\n");
      out.write("		text-align:left;\n");
      out.write("		padding-left:30px;\n");
      out.write("		padding-top:15px;\n");
      out.write("	\n");
      out.write("	}\n");
      out.write("	.groupIntro{\n");
      out.write("		height:35px;\n");
      out.write("		font-size:20px;\n");
      out.write("		font-weight:bold;\n");
      out.write("		text-align:left;\n");
      out.write("		padding-left:30px;\n");
      out.write("		padding-top:20px;\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.groupButtons{\n");
      out.write("		height:50px;\n");
      out.write("		font-size:10px;\n");
      out.write("		text-align:left;\n");
      out.write("		padding-top:20px;\n");
      out.write("		padding-left:20px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.gThumnail{\n");
      out.write("		position:absolute;\n");
      out.write("		transform:translate(-50%, -50%);\n");
      out.write("		max-width:100%; \n");
      out.write("		max-height:100%;\n");
      out.write("		-webkit-clip-path: inherit;\n");
      out.write("    	clip-path: inherit;\n");
      out.write("    	width: 100%;\n");
      out.write("   		height: 100%;\n");
      out.write("    	object-fit: cover;\n");
      out.write("    	border-top-left-radius:2em;\n");
      out.write("    	border-bottom-left-radius:2em;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	a.groupLink{\n");
      out.write("		text-decoration: none; /* 밑줄 없애기 */\n");
      out.write("  		color: black;\n");
      out.write("	}\n");
      out.write("	a.groupLink:hover{\n");
      out.write("		color:#ffab00\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("<!-- 	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> -->\r\n");
      out.write("	<title>Bootstrap demo</title>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("	<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("	<style>\r\n");
      out.write("		.bg{background-color: #FFAB00;}\r\n");
      out.write("		.navbar{height: 50px;}\r\n");
      out.write("		.image{height: 250px;}\r\n");
      out.write("		.mar{margin-left: 100px; margin-right: 100px;}\r\n");
      out.write("		.bo{border-top: 1px solid black; border-bottom: 1px solid black;}\r\n");
      out.write("		.a{font-weight: bold;}\r\n");
      out.write("	</style>\r\n");
      out.write("<script src=\"../js/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"navbar bg shadow-sm\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("	     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	  	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main.do\">\r\n");
      out.write("		<img src=\"resources/assets/gorriLogo.png\" class=\"rounded\" alt=\"...\">\r\n");
      out.write("	</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"nav-scroller py-1 mb-2 mar\">\r\n");
      out.write("    <nav class=\"nav d-flex justify-content-around bo\">\r\n");
      out.write("      <div> </div>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/miniMain.mi\">미니홈</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hobbyMain.hb\">취미</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupMain.gr\">모임</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"#\">마켓</a>\r\n");
      out.write("      <a class=\"p-2 link-secondary text-decoration-none a\" href=\"#\">공지</a>\r\n");
      out.write("      <div> </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("		<br><br>\n");
      out.write("		<br>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	<!-- 모임 검색창 + 모임 개설 버튼 -->\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	.selectCate{\r\n");
      out.write("	    	width:100%;\r\n");
      out.write("	    	text-align:left;\r\n");
      out.write("	    	border-color:lightgrey;\r\n");
      out.write("	    	\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	.selectCate::after{\r\n");
      out.write("	    display:none;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"text-align:center\">\r\n");
      out.write("<div class=\"btn-group nav-scroller py-1 mb-2\">\r\n");
      out.write("  <button type=\"button\" class=\"btn btn-white dropdown-toggle selectCate\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"  style=\"border:1px solid lightgrey;\">\r\n");
      out.write("   	전체\r\n");
      out.write("  </button> &nbsp;\r\n");
      out.write("  <ul class=\"dropdown-menu\">\r\n");
      out.write("	<li class=\"cateSel\"><a class=\"dropdown-item\">전체</a></li>\r\n");
      out.write("	<li><a class=\"dropdown-item cateSel\">모임장</a></li>\r\n");
      out.write("	<li><a class=\"dropdown-item cateSel\">모임명</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("  <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" style=\"width:350px; border: 1px solid lightgrey;\">\r\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\" style=\"background-color:gray; color:white; border:black\">Search</button>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("const label = document.querySelector('.selectCate');\r\n");
      out.write("const options = document.querySelectorAll('.dropdown-item');\r\n");
      out.write("// 클릭한 옵션의 텍스트를 라벨 안에 넣음\r\n");
      out.write("const handleSelect = function(item) {\r\n");
      out.write("  label.innerHTML = item.textContent;\r\n");
      out.write("  label.parentNode.classList.remove('active');\r\n");
      out.write("}\r\n");
      out.write("// 옵션 클릭시 클릭한 옵션을 넘김\r\n");
      out.write("options.forEach(function(option){\r\n");
      out.write("  option.addEventListener('click', function(){handleSelect(option)})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("        <br>\n");
      out.write("        <div class=\"gTitle\">\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupMaking.gr\"><button class=\"btn btn-outline-success\" type=\"button\" style=\"background-color:#ffab00; color:white; border:1px solid #ffab00\">모임 개설</button></a>\n");
      out.write("		</div><br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/243bcd4d8b.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("	<title>Gorri</title>\r\n");
      out.write("</head>\r\n");
      out.write("<Style>\r\n");
      out.write("\r\n");
      out.write("	table{\r\n");
      out.write("		margin:0 auto; text-align: center; width: 90%;\r\n");
      out.write("		border-top: 1.5px solid darkgray; border-bottom: 1.5px solid darkgray;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	.category{margin-left:100px; margin-right: 100px;}\r\n");
      out.write("	.categorys{width: 70px; cursor: pointer;  padding-top: 25px; padding-bottom: 20px;}\r\n");
      out.write("  	.category-name{font-size: 13px; text-decoration: none; color: black;} /* 카테고리 항목 글자크기 */\r\n");
      out.write("  	.fa-solid{font-size: 25px;} /* 아이콘 크기 */\r\n");
      out.write("  	.categorys:hover{color: #ffaa00;}\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("</Style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("    <!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"category\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"margin\"></td>\r\n");
      out.write("				<td class=\"categorys\"><i class=\"fa-solid fa-paintbrush\"></i><br><a class=\"category-name\">예술</a></td>\r\n");
      out.write("				<td class=\"categorys\"><i class=\"fa-solid fa-baseball\"></i><br><a class=\"category-name\">운동</a></td>\r\n");
      out.write("				<td class=\"categorys\"><i class=\"fa-solid fa-utensils\"></i><br><a class=\"category-name\">음식</a></td>\r\n");
      out.write("				<td class=\"categorys\"><i class=\"fa-solid fa-suitcase-rolling\"></i><br><a class=\"category-name\">여행</a></td>\r\n");
      out.write("				<td class=\"categorys\"><i class=\"fa-solid fa-pencil\"></i><br><a class=\"category-name\">창작</a></td>\r\n");
      out.write("				<td class=\"categorys\"><i class=\"fa-solid fa-graduation-cap\"></i><br><a class=\"category-name\">자기계발</a></td>\r\n");
      out.write("				<td class=\"margin\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("  	<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 모임 목록 입니다.  -->\n");
      out.write("<div align=\"center\" style=\"margin:30px; margin-left:auto; margin-right:auto;\">\n");
      out.write("   	<table class=\"groupTable2\"  style=\"border:2px solid #ffab00; border-radius:2em;\" >\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupPic\" rowspan =\"3\">\n");
      out.write("						<img src=\"resources/assets/musical.jpg\" class=\"gThumnail\">\n");
      out.write("					</td>\n");
      out.write("					<td class=\"groupTitle\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupDetailY.gr\" class=\"groupLink\">오페라의 유령</a></td>\n");
      out.write("				</tr>				\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupIntro\">오페라의 유령 얘기할 사람</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td style=\"text-align:right; padding-right:20px; height:80px;paddding-bottom:20px;\">\n");
      out.write("						<img src=\"resources/assets/heart.png\" style=\"width:25px; height:25px; cursor:pointer;\"> \n");
      out.write("						<span>10</span>\n");
      out.write("					</td> \n");
      out.write("				</tr>\n");
      out.write("	</table> \n");
      out.write("   	<table class=\"groupTable2\"  style=\"border:2px solid #ffab00; border-radius:2em;\" >\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupPic\" rowspan =\"3\">\n");
      out.write("						<img src=\"resources/assets/marvel.jpg\" class=\"gThumnail\">\n");
      out.write("					</td>\n");
      out.write("					<td class=\"groupTitle\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupDetailN.gr\" class=\"groupLink\">영화를 사랑하는 모임</a></td>\n");
      out.write("				</tr>				\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupIntro\">같이 영화 볼 사람 모집</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td style=\"text-align:right; padding-right:20px; height:80px;paddding-bottom:20px;\">\n");
      out.write("						<img src=\"resources/assets/heart.png\" style=\"width:25px; height:25px; cursor:pointer;\"> \n");
      out.write("						<span>10</span>\n");
      out.write("					</td> \n");
      out.write("				</tr>\n");
      out.write("	</table> \n");
      out.write("   	<table class=\"groupTable2\"  style=\"border:2px solid #ffab00; border-radius:2em;\" >\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupPic\" rowspan =\"3\">\n");
      out.write("						<img src=\"resources/assets/knitting.jpg\" class=\"gThumnail\">\n");
      out.write("					</td>\n");
      out.write("					<td class=\"groupTitle\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupDetailAdmin.gr\" class=\"groupLink\">뜨개뜨개</a></td>\n");
      out.write("				</tr>				\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupIntro\">뜨개질 정보 공유</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td style=\"text-align:right; padding-right:20px; height:80px;paddding-bottom:20px;\">\n");
      out.write("						<img src=\"resources/assets/heart.png\" style=\"width:25px; height:25px; cursor:pointer;\"> \n");
      out.write("						<span>10</span>\n");
      out.write("					</td> \n");
      out.write("				</tr>\n");
      out.write("	</table> \n");
      out.write("   	<table class=\"groupTable2\"  style=\"border:2px solid #ffab00; border-radius:2em;\" >\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupPic\" rowspan =\"3\">\n");
      out.write("						<img src=\"resources/assets/musical.jpg\" class=\"gThumnail\">\n");
      out.write("					</td>\n");
      out.write("					<td class=\"groupTitle\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupDetailY.gr\" class=\"groupLink\">오페라의 유령</a></td>\n");
      out.write("				</tr>				\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupIntro\">오페라의 유령 얘기할 사람</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td style=\"text-align:right; padding-right:20px; height:80px;paddding-bottom:20px;\">\n");
      out.write("						<img src=\"resources/assets/heart.png\" style=\"width:25px; height:25px; cursor:pointer;\"> \n");
      out.write("						<span>10</span>\n");
      out.write("					</td> \n");
      out.write("				</tr>\n");
      out.write("	</table> \n");
      out.write("   	<table class=\"groupTable2\"  style=\"border:2px solid #ffab00; border-radius:2em;\" >\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupPic\" rowspan =\"3\">\n");
      out.write("						<img src=\"resources/assets/musical.jpg\" class=\"gThumnail\">\n");
      out.write("					</td>\n");
      out.write("					<td class=\"groupTitle\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/groupDetailY.gr\" class=\"groupLink\">오페라의 유령</a></td>\n");
      out.write("				</tr>				\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"groupIntro\">오페라의 유령 얘기할 사람</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td style=\"text-align:right; padding-right:20px; height:80px;paddding-bottom:20px;\">\n");
      out.write("						<img src=\"resources/assets/heart.png\" style=\"width:25px; height:25px; cursor:pointer;\"> \n");
      out.write("						<span>10</span>\n");
      out.write("					</td> \n");
      out.write("				</tr>\n");
      out.write("	</table> \n");
      out.write(" </div>\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	 <script src=\"https://kit.fontawesome.com/243bcd4d8b.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.footer-bg{background: rgba(255, 170, 0, 0.7); width: 100%;} /*헤더 색깔은 #FFAB00*/\r\n");
      out.write("	\r\n");
      out.write("	.text{color: white;}\r\n");
      out.write("	.logo{width: 200px;}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("    <title>Gorri</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("    <!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->\r\n");
      out.write("    <br><br>\r\n");
      out.write("<div class=\"footer-bg\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	  <footer class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4\">\r\n");
      out.write("	    <p class=\"col-md-4 mb-0 text\">&copy; 2023 Company, Inc</p>\r\n");
      out.write("	\r\n");
      out.write("	    <a href=\"/\" class=\"col-md-4 d-flex align-items-center justify-content-center\">\r\n");
      out.write("	      <img class=\"logo\" src=\"resources/assets/gorriLogo.png\">\r\n");
      out.write("	    </a>\r\n");
      out.write("	    \r\n");
      out.write("	    <ul class=\"nav col-md-4 justify-content-end\">\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\">Home</a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\"><i class=\"fa-brands fa-twitter\"></i></a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\"><i class=\"fa-brands fa-facebook\"></i></a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\"><i class=\"fa-brands fa-instagram\"></i></a></li>\r\n");
      out.write("	      <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text\">About</a></li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	  </footer>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/group/../common/top.jsp(23,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/group/../common/top.jsp(23,0) '${ pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/group/../common/top.jsp(23,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/group/../common/top.jsp(23,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/group/../common/top.jsp(27,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		     <nav class=\"d-inline-flex mt-md-0 ms-md-auto\">\r\n");
          out.write("		       <a class=\"me-3 py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login.me\">로그인</a>\r\n");
          out.write("		       <a class=\"py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/join.me\">회원가입</a>\r\n");
          out.write("		     </nav>\r\n");
          out.write("		  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/group/../common/top.jsp(33,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \r\n");
          out.write("				  	\r\n");
          out.write("	     <nav class=\"d-inline-flex mt-md-0 ms-md-auto\">\r\n");
          out.write("	     	   <a class=\"me-3 py-2 text-white text-decoration-none\" style=\"color:lightgrey\" disabled >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</a>\r\n");
          out.write("		       <a class=\"me-3 py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout.me\">로그아웃</a>\r\n");
          out.write("		       <a class=\"py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/updateMyInfo.me\">내정보수정</a>\r\n");
          out.write("		       ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	     </nav>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/group/../common/top.jsp(39,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.isAdmin eq 'Y' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		       &nbsp; &nbsp; <a class=\"py-2 text-white text-decoration-none\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/adminDash.ad\">관리자페이지</a>\r\n");
          out.write("		       ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
